version: '2.3'

services:
  sea-orm-play:
    build: .
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:pass@postgres-docker/sea_orm_play
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    hostname: postgres-docker
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: sea_orm_play
    